<?php // vim: set expandtab tabstop=4 shiftwidth=4:

$levels = array(
    'bl2' => array(
            array('Ardorton Station', 'Sage_PowerStation_P'),
            array('Arena (final boss)', 'Iris_DL1_TAS_P'),
            array('Arena', 'Iris_DL1_P'),
            array('Arid Nexus - Badlands', 'Stockade_P'),
            array('Arid Nexus - Boneyard', 'Fyrestone_P'),
            array('Backburner', 'Backburner_P'),
            array('Badass Crater Bar', 'Iris_Moxxi_P'),
            array('Badass Crater of Badassitude', 'Iris_Hub_P'),
            array('Beatdown', 'Iris_DL2_P'),
            array('Bloodshot Ramparts', 'DamTop_P'),
            array('Bloodshot Stronghold', 'Dam_P'),
            array('Bunker', 'Boss_Cliffs_P'),
            array('Burrows', 'Sandworm_P'),
            array('Candlerakk\'s Crag', 'Sage_Cliffs_P'),
            array('Caustic Caverns', 'Caverns_P'),
            array('Control Core Angel', 'VOGChamber_P'),
            array('Dahl Abandon', 'OldDust_P'),
            array('Dark Forest', 'Dark_Forest_P'),
            array('Dragon Keep', 'CastleKeep_P'),
            array('Dust', 'Interlude_P'),
            array('End of the Line', 'TundraTrain_P'),
            array('Eridium Blight', 'Ash_P'),
            array('Fallen Helios', 'Helios_P'),
            array('Fight for Sanctuary', 'SanctIntro_P'),
            array('Fink\'s Slaughterhouse', 'BanditSlaughter_P'),
            array('Flamerock Refuge', 'Village_P'),
            array('Forge', 'Iris_DL3_P'),
            array('Fridge', 'Fridge_P'),
            array('Friendship Gulag', 'HypInterlude_P'),
            array('Frostburn Canyon', 'IceCanyon_P'),
            array('Gluttony Gulch', 'Hunger_P'),
            array('H.S.S. Terminus', 'Sage_HyperionShip_P'),
            array('Hallowed Hollow', 'Pumpkin_Patch_P'),
            array('Hatred\'s Shadow', 'CastleExterior_P'),
            array('Hayter\'s Folly', 'Orchid_Caves_P'),
            array('Hero\'s Pass', 'FinalBossAscent_P'),
            array('Highlands Outwash', 'Outwash_P'),
            array('Highlands', 'Grass_P'),
            array('Holy Spirits', 'Luckys_P'),
            array('Hunter\'s Grotto', 'Sage_Underground_P'),
            array('Immortal Woods', 'Dead_Forest_P'),
            array('Lair of Infinite Agony', 'Dungeon_P'),
            array('Leviathan\'s Lair', 'Orchid_WormBelly_P'),
            array('Lynchwood', 'Grass_Lynchwood_P'),
            array('Magnys Lighthouse', 'Orchid_Spire_P'),
            array('Marcus\'s Mercenary Shop', 'Xmas_P'),
            array('Mines of Avarice', 'Mines_P'),
            array('Mt. Scarab Research Center', 'ResearchCenter_P'),
            array('Murderlin\'s Temple', 'TempleSlaughter_P'),
            array('Natural Selection Annex', 'CreatureSlaughter_P'),
            array('Oasis', 'Orchid_OasisTown_P'),
            array('Opportunity', 'HyperionCity_P'),
            array('Ore Chasm', 'RobotSlaughter_P'),
            array('Paradise Sanctum', 'GaiusSanctuary_P'),
            array('Pyro Pete\'s Bar', 'Iris_DL2_Interior_P'),
            array('Raid on Digistruct Peak', 'TestingZone_P'),
            array('Rotgut Distillery', 'Distillery_P'),
            array('Rustyards', 'Orchid_ShipGraveyard_P'),
            array('Sanctuary (post liftoff)', 'SanctuaryAir_P'),
            array('Sanctuary (pre liftoff)', 'Sanctuary_P'),
            array('Sanctuary Hole', 'Sanctuary_Hole_P'),
            array('Sawtooth Cauldron', 'CraterLake_P'),
            array('Scylla\'s Grove', 'Sage_RockForest_P'),
            array('Southern Raceway', 'Iris_Hub2_P'),
            array('Southern Shelf - Bay', 'Cove_P'),
            array('Southern Shelf', 'SouthernShelf_P'),
            array('Southpaw Steam + Power', 'SouthpawFactory_P'),
            array('Terramorphous Peak', 'ThresherRaid_P'),
            array('Thousand Cuts', 'Grass_Cliffs_P'),
            array('Three Horns Divide', 'Ice_P'),
            array('Three Horns Valley', 'Frost_P'),
            array('Tundra Express', 'TundraExpress_P'),
            array('Unassuming Docks', 'Docks_P'),
            array('Vault of the Warrior', 'Boss_Volcano_P'),
            array('Wam Bam Island', 'Easter_P'),
            array('Washburne Refinery', 'Orchid_Refinery_P'),
            array('Wildlife Exploitation Preserve', 'PandoraPark_P'),
            array('Windshear Waste', 'Glacial_P'),
            array('Winged Storm', 'DungeonRaid_P'),
            array('Writhing Deep', 'SandwormLair_P'),
            array('Wurmwater', 'Orchid_SaltFlats_P'),
        ),
    'tps' => array(
            array('Abandoned Training Facility', 'MoonSlaughter_P'),
            array('Cluster 00773 P4ND0R4', 'Ma_LeftCluster_P'),
            array('Cluster 99002 0V3RL00K', 'Ma_RightCluster_P'),
            array('Concordia', 'Spaceport_P'),
            array('Cortex', 'Ma_SubBoss_P'),
            array('Crisis Scar', 'ComFacility_P'),
            array('Deck 13 1/2', 'Ma_Deck13_P'),
            array('Deck 13.5', 'Ma_FinalBoss_P'),
            array('Eleseer', 'InnerCore_P'),
            array('Eye of Helios', 'LaserBoss_P'),
            array('Helios Station', 'MoonShotIntro_P'),
            array('Holodome', 'Eridian_Slaughter_P'),
            array('Hyperion Hub of Heroism', 'CentralTerminal_P'),
            array('Jack\'s Office', 'JacksOffice_P'),
            array('Lunar Launching Station', 'Laser_P'),
            array('Meriff\'s Office', 'Meriff_P'),
            array('Motherlessboard', 'Ma_Motherboard_P'),
            array('Nexus', 'Ma_Nexus_P'),
            array('Outfall Pumping Station', 'Digsite_Rk5arena_P'),
            array('Outlands Canyon', 'Outlands_P2'),
            array('Outlands Spur', 'Outlands_P'),
            array('Pity\'s Fall', 'Wreck_P'),
            array('Regolith Range', 'Deadsurface_P'),
            array('Research and Development', 'RandDFacility_P'),
            array('Serenity\'s Waste', 'Moonsurface_P'),
            array('Stanton\'s Liver', 'StantonsLiver_P'),
            array('Sub-Level 13', 'Sublevel13_P'),
            array('Subconscious', 'Ma_Subconscious_P'),
            array('Titan Industrial Facility', 'DahlFactory_P'),
            array('Titan Robot Production Plant', 'DahlFactory_Boss'),
            array('Triton Flats', 'Moon_P'),
            array('Tycho\'s Ribs', 'Access_P'),
            array('Veins of Helios', 'InnerHull_P'),
            array('Vorago Solitude', 'Digsite_P'),
        ),
);
$levels_by_id = array('bl2' => array(), 'tps' => array());
foreach ($levels as $game => $level_list)
{
    foreach ($level_list as $level_tuple) {
        $levels_by_id[$game][$level_tuple[1]] = $level_tuple[0];
    }
}
